store: 131
products:
  - https://www.microcenter.com/product/486575/zero-w
  - https://www.microcenter.com/product/608166/4-model-b---1gb-ddr4
  - https://www.microcenter.com/product/608186/4-model-b---2gb-ddr4
  - https://www.microcenter.com/product/608187/4-model-b---4gb-ddr4
